Merge Module 03 → Master
sjubusel/mjc_school pull request #5
Opened 2021-01-28 08:45 UTC by sjubusel

2021-02-03 08:37 UTC, mvladmoss requested changes

2021-02-03 14:40 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/domain/GiftCertificate.java
> +    @Column
Resolved

2021-02-03 14:41 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/domain/GeneralEntity.java
> +public abstract class GeneralEntity<T> {
The word (adjective) "general" means affecting or concerning all or most things, in own case "Entities" (рус. прил. общий, родовой (о понятии) , общего характера (характерный для определённого класса, типа), обычный). Synonyms: common, basic, etc.

In the previous  module 02 I used a name "Entity" for this class, but
in this module 03 I used a name "GeneralEntity", because in this module 03 I ought to implement JPA API and used an annotation @Entity (@javax.persistence.Entity) in subclasses of this class (GiftCertificate, Order, OrderPosition, Tag, User).
I cannot replace both an aforementioned annotation and class Entity with their "import"-statements at the same time: 
-import javax.persistence.Entity;
-import com.epam.esm.model.domain.Entity
because of ambiguity of name Entity for a compiler.

Should I use the following statement "@javax.persistence.Entity" over aforementioned subclasses instead of using the following: 
"@Entity"
and 
"import javax.persistence.Entity;"?

2021-02-03 14:41 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/domain/GiftCertificate.java
> +    @JoinTable(name = "join_certificates_tags_table",
Resolved

2021-02-03 14:41 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/domain/Order.java
> +    @Transient
The field "private BigDecimal price" marked as transient is deleted, as well as annotation @transient.

The only reason to have this field was to make domain and dto classes equal

2021-02-03 14:41 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/entity_listener/GeneralEntityListener.java
> +package com.epam.esm.model.entity_listener;
Resolved: a folder "entity_listener" renamed, a new name is "listener"

2021-02-03 14:41 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/domain/User.java
> +    private Set<Order> orders;
Resolved. Thanks, I revised the usage of unidirectional and bidirectional associations:
-I deleted bidirectional relations between GiftCertificate → Set<OrderPosition> orderPositions
-I deleted bidirectional relations between User → Set<Order> orders

2021-02-03 14:42 UTC, sjubusel commented on module_03/repository/src/main/java/com/epam/esm/repository/GiftCertificateRepository.java
> +    void deleteLinkBetweenGiftCertificateAndTags(GiftCertificate certificate);
Resolved: unused method "deleteLinkBetweenGiftCertificateAndTags()" is deleted

2021-02-03 14:49 UTC, sjubusel commented on module_03/repository/src/main/java/com/epam/esm/repository/impl/DefaultGiftCertificateRepository.java
> +public class DefaultGiftCertificateRepository extends GeneralCrudRepository<GiftCertificate, Long>
I partially passed a private tutorial, where it was said that there are two naming strategies of classes that are implementations of interfaces:
1) Default<MY_INTERFACE_NAME>;
2)<MY_INTERFACE_NAME>Impl;

However, I renamed all "defaults" into "impls" and in the future I won't use "defaults" :)

2021-02-05 08:26 UTC, Mazorakopf commented on module_03/repository/src/main/java/com/epam/esm/repository/impl/OrderRepositoryImpl.java
> +    @Autowired
_Recommendation:_ you can omit this annotation if you have one constructor in the class.

Link: https://stackoverflow.com/questions/41092751/spring-injects-dependencies-in-constructor-without-autowired-annotation/41092831

2021-02-05 08:31 UTC, Mazorakopf commented on module_03/service/src/main/java/com/epam/esm/service/converter/impl/GiftCertificateConverter.java
> +@Mapper(componentModel = "spring", injectionStrategy = InjectionStrategy.CONSTRUCTOR, uses = TagConverter.class)
👍

2021-02-05 08:46 UTC, Mazorakopf commented on module_03/web/src/main/java/com/epam/esm/web/exception/GeneralExceptionHandler.java
> +@ControllerAdvice
_Recommendation:_ Instead of this annotation, you can use @RestControllerAdvice.

_Link_: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RestControllerAdvice.html

2021-02-05 08:50 UTC, Mazorakopf commented on module_03/web/src/main/java/com/epam/esm/web/controller/GiftCertificateController.java
> +        return new ResponseEntity<>(updatedGiftCertificate, HttpStatus.OK);
If you are using a static ResponseEntity builder, then use it everywhere.

_Example_: ResponseEntity.ok(updatedGiftCertificate);

_Link_: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html

![image](https://user-images.githubusercontent.com/33939403/107011140-50a3a280-67a8-11eb-8032-52fb13d37630.png)

2021-02-05 08:51 UTC, Mazorakopf commented on module_03/web/src/main/java/com/epam/esm/web/exception/GeneralExceptionHandler.java
> +        return new ResponseEntity<>(errorInfo, HttpStatus.NOT_FOUND);
Use static RespponseEntity builder like in controller classes

2021-02-05 08:53 UTC, Mazorakopf commented on module_03/web/src/main/java/com/epam/esm/web/controller/TagController.java
> +    private void applyHateoasActionsForSeparateTag(TagDto tagDto) {
_Recommendation_: Maybe you should move this method to a separate class?

2021-02-05 08:56 UTC, Mazorakopf commented on module_03/web/src/main/java/com/epam/esm/web/controller/TagController.java
> +    @GetMapping("/main_tag")
Maybe just call /main

2021-02-05 09:27 UTC, Mazorakopf approved these changes

2021-02-05 14:39 UTC, sjubusel commented on module_03/repository/src/main/java/com/epam/esm/repository/impl/OrderRepositoryImpl.java
> +    @Autowired
Fixed, @ Annotation annotations are also omitted in the same situations in UserRepositoryImpl, TagRepositoryImpl, OrderRepositoryImpl, GiftCertificateRepositoryImpl.

2021-02-05 14:39 UTC, sjubusel commented on module_03/service/src/main/java/com/epam/esm/service/converter/impl/GiftCertificateConverter.java
> +@Mapper(componentModel = "spring", injectionStrategy = InjectionStrategy.CONSTRUCTOR, uses = TagConverter.class)
Thanks

2021-02-05 14:39 UTC, sjubusel commented on module_03/web/src/main/java/com/epam/esm/web/exception/GeneralExceptionHandler.java
> +@ControllerAdvice
Fixed
I've become acquainted with the materials about @ RestControllerAdvice You provided

2021-02-05 14:40 UTC, sjubusel commented on module_03/web/src/main/java/com/epam/esm/web/controller/GiftCertificateController.java
> +        return new ResponseEntity<>(updatedGiftCertificate, HttpStatus.OK);
Fixed
I've looked through all similar situations, ResponseEntity's constructor have been replaced with ResponseEntity's builder in the following places (except for @RestControllerAdvice: they will be shown in the related fix report below):
►com.epam.esm.web.controller.GiftCertificateController#update
►com.epam.esm.web.controller.TagController#update
In the future I will treat initialization of object of this class in the same way, that is using its "builder"

2021-02-05 14:41 UTC, sjubusel commented on module_03/web/src/main/java/com/epam/esm/web/exception/GeneralExceptionHandler.java
> +        return new ResponseEntity<>(errorInfo, HttpStatus.NOT_FOUND);
Fixed
These issues are fixed in all methods annotated with @ ExceptionHandler annotation in the way I did in the controllers classes

2021-02-05 14:41 UTC, sjubusel commented on module_03/web/src/main/java/com/epam/esm/web/controller/TagController.java
> +    @GetMapping("/main_tag")
Fixed
It's a very good idea, indeed

2021-02-05 17:06 UTC, sjubusel commented on module_03/web/src/main/java/com/epam/esm/web/controller/TagController.java
> +    private void applyHateoasActionsForSeparateTag(TagDto tagDto) {
Fixed
All similar situations are refactored: interface HateoasActionsAppender and implementations for every controller (GiftCertificateHateoasActionsAppender, OrderHateoasActionsAppender, TagHateoasActionsAppender, UserHateoasActionsAppender) are created.

P.S. @Mazorakopf all your changes and recommendations are fixed.

2021-02-07 21:13 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/domain/GeneralEntity.java
> +public abstract class GeneralEntity<T> {
Resolved
This issue is discussed verbally. The results:
import javax.persistence.Entity
AND 
public abstract class Entity<T>

2021-02-08 07:58 UTC, mvladmoss approved these changes

2021-02-12 09:52 UTC, nikskonda commented on module_03/model/src/main/java/com/epam/esm/model/dto/UserDto.java
> +    @Pattern(regexp = "[+][0-9]{1,3}[ ][(][0-9]{2,3}[)][ ][1-9][0-9]{2}[-][0-9]{2}[-][0-9]{2}",
FYI: 
\\d цифровой символ
\\D нецифровой символ

2021-02-12 10:18 UTC, nikskonda commented on module_03/repository/src/main/java/com/epam/esm/repository/specification/impl/GiftCertificateSpecification.java
> +    private static final Integer PAGE_SIZE = 20;
It is a bad idea to hardcode the page size. You need to rebuild the jar to change this value. In my opinion, it's better to move to the settings file.

The user could set this value. Limit to the maximum.

2021-02-12 10:26 UTC, nikskonda commented on module_03/repository/src/main/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImpl.java
> +        Predicate finalPredicate = criteriaBuilder.and(nameCondition, descriptionCondition, priceCondition,
I think better to move "predicate" logic to separate class.

2021-02-12 12:29 UTC, sjubusel commented on module_03/model/src/main/java/com/epam/esm/model/dto/UserDto.java
> +    @Pattern(regexp = "[+][0-9]{1,3}[ ][(][0-9]{2,3}[)][ ][1-9][0-9]{2}[-][0-9]{2}[-][0-9]{2}",
Fixed
I am acquainted with speсial regex tokens, including "\d" / "\D". But it was more convenient for me to use the "digits"-combination ([0-9]) instead of "special-regex-token"-combination [\\d], moreover both the aforementioned combinations have the same length: 3 characters. 
However, in the future I will use aforementioned tokens instead of explicit definitions of regexp if it is necessary.

2021-02-12 18:24 UTC, sjubusel commented on module_03/repository/src/main/java/com/epam/esm/repository/specification/impl/GiftCertificateSpecification.java
> +    private static final Integer PAGE_SIZE = 20;
Fixed
The following steps are accomplished:
•A new property: "page.default-page-size" is added into the "application-${spring,active.profile}.yaml" files;
#################
page:
  default-page-size: 20
#################
•An ability to specify a size of page is implemented for an API's client.

If a client doesn't define a page size manually, the default one from properties will be used.

2021-02-12 19:33 UTC, sjubusel commented on module_03/repository/src/main/java/com/epam/esm/repository/impl/GiftCertificateRepositoryImpl.java
> +        Predicate finalPredicate = criteriaBuilder.and(nameCondition, descriptionCondition, priceCondition,
Fixed:
All "predicate" logic has been moved to a newly created "com.epam.esm.repository.util.GiftCertificatePredicateBuilder#buildExistsPredicate" 

P.S. Nikita, all your change-requests are complete. Thanks for your review.

2021-02-15 10:03 UTC, nikskonda approved these changes

2021-02-15 10:08 UTC, nikskonda commented
Looks good, but it takes time to figure out. In the future, please try to keep it simple where possible.

2021-02-16 06:34 UTC, merged